### ISSUE TITLE
Rendering problem with multi-line class docstrings

### ISSUE THREAD

**Issue by cmarqu** [chrisjsewell/sphinx-sqlalchemy#14]
It looks like (multi-line) class docstrings should be dedented (e.g. with `textwrap.dedent`) to prevent them from being rendered like quotes in HTML output.

A simple `textwrap.dedent` doesn't work though due to the problem explained in https://stackoverflow.com/questions/75667657/how-to-dynamically-change-indentation-in-a-multiline-string,
the solution https://stackoverflow.com/a/75667889/ could be used.

**Comment by AlexTorx** [comment]
I am having the exact same issue, with multiline docstrings, that look like the following (to take same example as this package unit tests) :

```python
class UserMultilineDocstringD212(Base):
    """
    A ``user``.

    The user has a multi-line doctsring.

    This is the last line of the docstring.
    """

    __tablename__ = "dbusers_d212"
    __table_args__ = (UniqueConstraint("first_name", "last_name"),)
    pk = Column(types.Integer, primary_key=True)
    first_name = Column(types.String, doc="The name of the user.")
    last_name = Column(types.String(255), doc="The surname of the user.")
    dob = Column(types.Date, nullable=False, doc="The date of birth.")
```

@chrisjsewell I just cloned the repo and proposed a fix (with associated unit tests, using @cmarqu links above) but cannot push to any branch. What are the contributions guidelines ?

**Comment by cmarqu** [comment]
@AlexTorx You probably need to fork the repo first (easiest in the upper right in the GitHub web GUI) and open the PR from this fork.

**Comment by AlexTorx** [comment]
> @AlexTorx You probably need to fork the repo first (easiest in the upper right in the GitHub web GUI) and open the PR from this fork.

Yep it's been a while since last contribution to an open-source repo, kind of forgot how it worked. Thanks for the reminder ;)

PR has been created from a fork : https://github.com/chrisjsewell/sphinx-sqlalchemy/pull/15
